version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - POSTGRES_USER=tu_usuario
      - POSTGRES_PASSWORD=tu_contraseña
      - POSTGRES_DB=nombre_base_de_datos
      - POSTGRES_HOST=db
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: tu_usuario
      POSTGRES_PASSWORD: tu_contraseña
      POSTGRES_DB: nombre_base_de_datos
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
