version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ERIKpro02
      - POSTGRES_DB=cockmanager
      - POSTGRES_HOST=db
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ERIKpro02
      POSTGRES_DB: cockmanager
    ports:
      - "5433:5432"   # Cambia el puerto de PostgreSQL de 5432 a 5433
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"   # Cambia el puerto de PGAdmin de 5050 a 5051
    depends_on:
      - db

volumes:
  pgdata:
